In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
print(a.shape)

(4,)


In [5]:
b=np.array([[1,2,3,4],[1,2,3,4]])

In [7]:
print(b)
print(b.shape)

[[1 2 3 4]
 [1 2 3 4]]
(2, 4)


In [8]:
b.T

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [9]:
print(np.dot(b,b.T))

[[30 30]
 [30 30]]


In [17]:
matrix=np.random.randint(5,10,size=(3,4))
print(matrix)

[[7 8 5 7]
 [8 7 7 9]
 [7 9 9 9]]


In [19]:
np.min(matrix),np.max(matrix)

(5, 9)

In [20]:
p=np.array([1,2,-3,4,0])
print(np.argmax(p),np.argmin(p))


3 2


In [24]:
b=np.array([1,-2,3,4,5,1,234,0,0,1,0,-2,3,4,5])
c=np.unique(b,return_counts=True)

In [25]:
print(c)

(array([ -2,   0,   1,   3,   4,   5, 234]), array([2, 3, 3, 2, 2, 2, 1], dtype=int64))


In [29]:
idx=np.argmax(c[1])
print(c[0][idx])

0
