In [1]:
import numpy as np

In [4]:
a=np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [8]:
b=np.array([[1],[2],[3],[4],[5]])
print(b)

print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


# create array of zeros and ones

In [13]:
# Array of zeros
a=np.zeros((3,3))
print(a)
print(a.shape)

#Array of ones
b=np.ones((2,3))
print(b)
print(b.shape)

#identity matrix
c=np.eye(3)
print(c)
print(c.shape)

#array with constant value
d=np.full((3,4),9)
print(d)
print(d.shape)

#Array with random matrix
e=np.random.random((4,3))
print(e)
print(e.shape)



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]
(3, 4)
[[0.95508014 0.42469304 0.56863516]
 [0.97203084 0.8449424  0.34065857]
 [0.39306735 0.43957211 0.66439374]
 [0.54260161 0.95431207 0.12106507]]
(4, 3)


In [15]:
#datatypes
z=np.zeros((3,3),dtype=np.int64)
print(z)
print(z.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
int64


In [32]:
#Mathematical Operations

#Addition
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
print(a+b)
print(np.add(a,b))

#Multiplication
print(a*b)
print(np.multiply(a,b))

#Divide
print(a/b)
print(np.divide(a,b))

#Matrix multiplication
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8],[9,10],[11,12]])
print(a)
print(b)
print(a.dot(b))
print(np.dot(a,b))

#Multiplication of vector
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(a.dot(b))

#Stack
print(np.stack((a,b),axis=0))


#sum
print(np.sum(a))

a=np.array([[1,2],[3,4]])
print(np.sum(a))
print(np.sum(a,axis=0))

#Reshape

print(a.reshape((4,-1)))





[[ 8 10 12]
 [14 16 18]]
[[ 8 10 12]
 [14 16 18]]
[[ 7 16 27]
 [40 55 72]]
[[ 7 16 27]
 [40 55 72]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 58  64]
 [139 154]]
[[ 58  64]
 [139 154]]
30
[[1 2 3 4]
 [1 2 3 4]]
10
10
[4 6]
[[1]
 [2]
 [3]
 [4]]


[[ 7 16 27]
 [40 55 72]]
[[ 7 16 27]
 [40 55 72]]
