In [1]:
import numpy as np

In [4]:
a=np.arange(1,15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
np.random.shuffle(a)
a

array([ 5,  9,  2,  8, 11,  3,  7, 14,  1, 13,  6,  4, 12, 10])

In [19]:
#return value from standard normal distribution
a=np.random.randn(2,3)
print(a)
a=np.random.randint(3,10,size=5)
print(a)
a=np.random.choice([1,2,3,4,5],size=2,p=[0,0,0,0.5,0.5])
print(a)

[[-0.788841    1.07590121 -0.54241688]
 [-1.57251321 -0.49092487 -0.91956365]]
[5 9 5 9 4]
[5 5]
