<p style="color:red;"> Aman yadav </p>
<h1> Numpy functions - statistic </h1>   
    <ul>
    <li> min ,max </li>
    <li>mean </li>
    <li> average </li>
    <li> variance </li>
    <li> standard deviation</li>
    </ul>


In [3]:
import numpy as np

In [5]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
# get minimum among all
print(np.min(a))

# get minimum columnwise/rowise axis=0/1
print(np.min(a,axis=0))
# get maximum among all
print(np.max(a))

# get maximum columnwise/rowise axis=0/1
print(np.max(a,axis=0))

1
[1 2 3 4]
8
[5 6 7 8]


In [19]:
b=np.arange(5)
print(b)
# get mean
print(np.mean(b))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))
# get average ( average is weighted mean)
print(np.average(b,weights=[1,1,1,1,1]))


[0 1 2 3 4]
2.0
[3. 4. 5. 6.]
[2.5 6.5]
2.0


In [16]:
np.random.shuffle(b)
print(b)
# get median
print(np.median(b))

[0 1 3 4 2]
2.0


In [22]:
#standard deviation
# formula sqrt((xi-u)**2)/size)
mean=np.mean(b)
standard_deviation=np.sqrt(np.mean((b-mean)**2))
print(standard_deviation)
# using inbuild function
print(np.std(b))


1.4142135623730951
1.4142135623730951


In [23]:
# variance
print(standard_deviation**2)
print(np.var(b))

2.0000000000000004
2.0
